---
title: "Soil chem"
author: "Jane Fudyma"
date: "2023-07-31"
output: html_document
---

```{r}
library(tidyverse)
library(vegan)
library(ape)
library(heatmaply)
library(pheatmap)
library(ggplotify)
library(cowplot)
```

```{r}
env <- read_csv('../data/221102_soilpropertydata.csv')
env.plots <- env %>% select(-Type, -`lbs N/A`) #%>% column_to_rownames(var = 'Sample') 

(env.plots.tidy <- env.plots %>% gather(key = "Property", value = "Value", -Sample) %>% 
                  group_by(Property) %>% 
                  mutate(zValue = (Value - mean(Value))/sd(Value)) %>% 
                  select(Sample, Property, zValue) %>% 
                  spread(key = Property, value = zValue) %>% 
                  as.data.frame() %>% column_to_rownames(var="Sample"))


otu_dist <- as.matrix(vegdist(env.plots.tidy, method='euclidean')) 
pca <- pcoa(as.dist(otu_dist))
axes.env <- as.data.frame(pca$vectors)
axes.env$Soil <- substr(rownames(axes.env), 1, 2)
axes.env$Rep <- substr(rownames(axes.env), 4,5)

eigvalz <- round(pca$values$Relative_eig * 100, digits = 2)
eigvalz <- data.frame( PC = 1:length(eigvalz), Eigval = eigvalz)

pc1 <- paste("PC1 (", eigvalz[[1,2]], " %)", sep = "")
pc2 <- paste("PC2 (", eigvalz[[2,2]], " %)", sep = "")

(pca_plot <-  ggplot(axes.env, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(fill = Soil, shape = Rep), color = "black", size = 5, alpha = 0.9, show.legend = TRUE) +
  labs(title = "Soil Physicochemical Data: pH Experiment", x = pc1, y = pc2) +
  theme_linedraw(base_size = 16) +
  scale_fill_manual(values = c('darkslateblue','cornflowerblue', 'burlywood1'), labels = c("Forest", "Wetland", "Grassland")) +
  scale_shape_manual(values = c(24, 22, 21), name = "Replicate") +
  guides(fill=guide_legend(override.aes=list(shape=21))) +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 11, face="bold"),
    axis.title.x = element_text(size = 9, face = 'bold'),
    axis.title.y = element_text(size = 9, face = 'bold'),
    panel.grid.major = element_line(color = "gray80"),
    panel.grid.minor = element_line(color = "gray80")
  ))

colnames(env.plots.tidy)



names(env.plots.tidy) <- c("CaSat (%)", "Calcium (ppm)", "Copper (ppm)", "H Sat (%)", "Iron (ppm)", "KSat (%)", "Magnesium (ppm)", "Manganese (ppm)", "MgSat (%)", "NaSat (%)", "Nitrate-N (ppm)", "Phosphorous (ppm)", "Organic Matter (%)", "Potassium (ppm)", "Soluble Salts (mmho/cm)", "Sodium (ppm)", "Soil pH", "Sulfate-S (ppm)", "Sum of Cations (me/100g)", "Zinc (ppm)")

rownames(env.plots.tidy) <- c("F_BR1", "F_BR2", "F_BR3", "F_TR1", "W_BR1", "W_BR2", "W_BR3", "W_TR1", "G_BR1" , "G_BR2", "G_BR3", "G_TR1")

(hm.2.all <- pheatmap(env.plots.tidy, color = plasma(15)))
hm.2 <- as.grob(hm.2.all)

(top <- plot_grid(pca_plot, hm.2, ncol = 2, rel_widths = c(1,1.3), labels = c('A','B')) + theme(
    plot.background = element_rect(fill = "white", color = 'white'))) 
#ggsave('SoilPhysicochemistry_PCoA_Heatmap.png', p2, dpi = 300, width = 13, height = 5)
```

```{r}
env <- read_csv('../data/2309_EdaphicProperties_AllSoils_AllBufferChem.csv') %>% filter(Sample %in% c("BB_BR1", "BB_BR2","BB_BR3", "BB_TR1", "BB_BC_BR1", "BB_BC_BR2", "BB_BC_BR3", "BB_BC_TR1" ))
env.plots <- env %>% select(-Type, -Time, -`lbs N/A`) #%>% column_to_rownames(var = 'Sample') 

(env.plots.tidy <- env.plots %>% gather(key = "Property", value = "Value", -Sample) %>% 
                  group_by(Property) %>% 
                  mutate(zValue = (Value - mean(Value))/sd(Value)) %>% 
                  select(Sample, Property, zValue) %>% 
                  spread(key = Property, value = zValue) %>% 
                  as.data.frame() %>% column_to_rownames(var="Sample") %>% select(-"H Sat"))


otu_dist <- as.matrix(vegdist(env.plots.tidy, method='euclidean')) 
pca <- pcoa(as.dist(otu_dist))
axes.env <- as.data.frame(pca$vectors)
axes.env$Time <- c('4','4','4','2','1', '1', '1', '3')
axes.env$Rep <- c('BR','BR','BR','TR', 'BR','BR','BR','TR')
axes.env$Rep1 <- c('BR1','BR2','BR3','TR', 'BR1','BR2','BR3','TR')

eigvalz <- round(pca$values$Relative_eig * 100, digits = 2)
eigvalz <- data.frame( PC = 1:length(eigvalz), Eigval = eigvalz)

pc1 <- paste("PC1 (", eigvalz[[1,2]], " %)", sep = "")
pc2 <- paste("PC2 (", eigvalz[[2,2]], " %)", sep = "")

(pca_plot <-  ggplot(axes.env, aes(x = Axis.1, y = Axis.2)) +
  geom_point(aes(fill = Time, shape = Rep1), color = "black", size = 5, alpha = 0.9, show.legend = TRUE) +
  labs(title = "Soil Physicochemical Data: All Wetland Soil", x = pc1, y = pc2) +
  theme_linedraw(base_size = 16) +
  scale_fill_manual(values = c('#36D6E7', '#9BCCFD', '#81599F', '#0074DD'), name = "Sampling Time", labels = c('3/21 (pH Bio)', '11/21 (Chem Tech)', '12/21 (pH Tech)', '11/22 (Chem Bio)')) +
  scale_shape_manual(values = c(24, 22, 21, 23), name = "Replicate") +
  guides(fill=guide_legend(override.aes=list(shape=21))) +
  theme(
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    plot.title = element_text(size = 11, face="bold"),
    axis.title.x = element_text(size = 9, face = 'bold'),
    axis.title.y = element_text(size = 9, face = 'bold'),
    panel.grid.major = element_line(color = "gray80"),
    panel.grid.minor = element_line(color = "gray80")
  ))

names(env.plots.tidy) <- c("CaSat (%)", "Calcium (ppm)", "Copper (ppm)", "Iron (ppm)", "KSat (%)", "Magnesium (ppm)", "Manganese (ppm)", "MgSat (%)", "NaSat (%)", "Nitrate-N (ppm)", "Phosphorous (ppm)", "Organic Matter (%)", "Potassium (ppm)", "Soluble Salts (mmho/cm)", "Sodium (ppm)", "Soil pH", "Sulfate-S (ppm)", "Sum of Cations (me/100g)", "Zinc (ppm)")

rownames(env.plots.tidy) <- c("W_BC_BR1", "W_BC_BR2", "W_BC_BR3", "W_BC_TR1", "W_pH_BR1", "W_pH_BR2", "W_pH_BR3", "W_pH_TR1")

(hm.2.all <- pheatmap(env.plots.tidy, color = plasma(15)))
hm.2 <- as.grob(hm.2.all)

(bottom <- plot_grid(pca_plot, hm.2, ncol = 2, rel_widths = c(1,1.15), labels = c('C','D')) + theme(
    plot.background = element_rect(fill = "white", color = 'white'))) 
#ggsave('SoilPhysicochemistry_PCoA_Heatmap_Wetland_pHandBuffChem.png', p2, dpi = 300, width = 13, height = 5)
```

```{r}
(together <- plot_grid(top, bottom, ncol = 1))
ggsave('BufferChemSoilChemData.png', together, width = 15, height = 10, dpi = 400)
```

